.PHONY: all clean

all:
	cd tcg_api && make all
	cd Kinetic_Security && make all

kinetic:
	cd tcg_api && make kinetic
	cd Kinetic_Security && make kinetic

clean:
	cd tcg_api && make clean
	cd Kinetic_Security && make clean

kclean:
	cd tcg_api && make kclean
	cd Kinetic_Security && make kclean

