#ifndef KINETIC_VERSION_INFO_H_
#define KINETIC_VERSION_INFO_H_
#define BUILD_DATE ("Sun Apr 12 19:07:56 MDT 2020")
#define CURRENT_SEMANTIC_VERSION ("09.02.08")
#define GIT_HASH ("893f8e2-dirty")
#define CURRENT_PROTOCOL_VERSION ("4.0.1")
#define KINETIC_PROTO_GIT_HASH ("f8d5d18")
#endif  // KINETIC_VERSION_INFO_H_
