.PHONY: all clean

all:
	cd external-libs && make all
	cd api && make all
	cd tools && make all
	cd PAM && make all

kinetic:
	cd external-libs && make all
	cd api && make all
	cd PAM && make all

clean:
	cd external-libs && make clean
	cd api && make clean
	cd tools && make clean
	cd PAM && make clean

kclean:
	cd external-libs && make clean
	cd api && make clean
	cd PAM && make clean
