cp *.a $1
cp kmem/*.a  $1
cp ./K_api/Kinetic_Security/api/libksapi.a $1
cp K_api/Kinetic_Security/external-libs/PBKDFlib/*.a $1
cp  lldp/*.a  $1
cp  qual/*.a  $1
cp smrdb/*.a $1
cp ha_zac_cmds/*.a $1
cp K_api/tcg_api/transports/*.a $1
cp K_api/tcg_api/api/*.a $1
cp vendor/src/kinetic_cpp_client/*.a $1
cp /usr/lib/x86_64-linux-gnu/libssl.a $1
cp /usr/lib/x86_64-linux-gnu/libcrypto.a $1
cp /usr/local/lib/libglog.a $1
cp /usr/local/lib/libgmock.a $1
cp /usr/local/lib/libgtest.a $1
cp /usr/local/lib/libprotobuf.a $1
cp /usr/local/lib/libprotoc.a $1
cp /usr/local/lib/libgflags.a $1
cp /usr/local/lib/libgflags_nothreads.a $1
