#!/bin/bash

# This script is designed to handle the generation of a temporary private key
# and certificate for SSL so that integration tests can run without having to
# worry about them. The script creates a key and certificate, runs the server,
# and then removes the key and certificate afterward.

# Get the directory containing this script
containing_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$containing_directory"

PRIVATE_KEY=test_private_key.pem
CERTIFICATE=test_certificate.pem
CLUSTER_VERSION_PATH=cluster_version
PRIMARY_DB_PATH=primary.db
METADATA_DB_PATH=metadata.db
FILE_STORE_PATH=file_store

openssl req -x509 -nodes -newkey rsa:1024 -keyout "$PRIVATE_KEY" -out "$CERTIFICATE" 2>/dev/null << EOF
US
Cool State
Cool City
Internet Widgits Pty Ltd
Department of Cool Stuff
Cool Server
me@example.com
This line intentionally blank
EOF

if [ "$1" = "--clear_database" ]; then
    rm -rf $CLUSTER_VERSION_PATH $PRIMARY_DB_PATH $METADATA_DB_PATH $FILE_STORE_PATH
fi

exec ./kineticd --private_key="$PRIVATE_KEY" --certificate="$CERTIFICATE" \
    --cluster_version_path=$CLUSTER_VERSION_PATH --primary_db_path=$PRIMARY_DB_PATH \
    --metadata_db_path=$METADATA_DB_PATH --file_store_path=$FILE_STORE_PATH 1>/dev/null 2>/dev/null
