#!/bin/sh

KINETIC_HOME=/opt/kinetic

# SSL credentials
CERTIFICATE_PATH=/mnt/util/certificates
CERTIFICATE=$CERTIFICATE_PATH/certificate.pem
PRIVATE_KEY=$CERTIFICATE_PATH/private_key.pem

# Storage configuration
UTIL_PARTITION=/mnt/util
DATA_PARTITION=/mnt/store
META_DATA_PARTITION=/mnt/metadata
METADATA_DB_PATH=$META_DATA_PARTITION/metadata/metadata.db
PRIMARY_DB_PATH=$DATA_PARTITION/primary.db
FILE_STORE_PATH=$DATA_PARTITION/file_store
UPDATE_TMP_DIR=$UTIL_PARTITION/tmp
CLUSTER_VERSION_PATH=$DATA_PARTITION/cluster_version
PREUSED_FILE_PATH=$KINETIC_HOME/fsize
LOG_FILE_PATH=$UTIL_PARTITION/log.txt
OLD_LOG_FILE_PATH=$UTIL_PARTITION/previousLog
COMMAND_LOG_FILE_PATH=$UTIL_PARTITION/command_log.txt
OLD_COMMAND_LOG_FILE_PATH=$UTIL_PARTITION/command_previousLog
STALE_DATA_LOG_FILE_PATH=$UTIL_PARTITION/stale_log.txt
OLD_STALE_DATA_LOG_FILE_PATH=$UTIL_PARTITION/stale_previouslog
KEY_VALUE_LOG_FILE_PATH=$UTIL_PARTITION/key_value_log.txt
OLD_KEY_VALUE_LOG_FILE_PATH=$UTIL_PARTITION/key_value_previousLog
KEY_SIZE_LOG_FILE_PATH=$UTIL_PARTITION/key_size_log.txt
OLD_KEY_SIZE_LOG_FILE_PATH=$UTIL_PARTITION/key_size_previousLog
VALUE_SIZE_LOG_FILE_PATH=$UTIL_PARTITION/value_size_log.txt
OLD_VALUE_SIZE_LOG_FILE_PATH=$UTIL_PARTITION/value_size_previousLog
LATENCY_THRESHOLD=2000

mkdir -p $UPDATE_TMP_DIR
$KINETIC_HOME/kineticd --certificate=$CERTIFICATE --private_key=$PRIVATE_KEY \
    --firmware_update_tmp_dir=$UPDATE_TMP_DIR \
    --preused_file_path=$PREUSED_FILE_PATH \
    --log_file_path=$LOG_FILE_PATH \
    --old_log_file_path=$OLD_LOG_FILE_PATH \
    --command_log_file_path=$COMMAND_LOG_FILE_PATH \
    --old_command_log_file_path=$OLD_COMMAND_LOG_FILE_PATH \
    --stale_data_log_file_path=$STALE_DATA_LOG_FILE_PATH \
    --old_stale_data_log_file_path=$OLD_STALE_DATA_LOG_FILE_PATH \
    --key_value_log_file_path=$KEY_VALUE_LOG_FILE_PATH \
    --old_key_value_log_file_path=$OLD_KEY_VALUE_LOG_FILE_PATH \
    --key_size_log_file_path=$KEY_SIZE_LOG_FILE_PATH \
    --old_key_size_log_file_path=$OLD_KEY_SIZE_LOG_FILE_PATH \
    --value_size_log_file_path=$VALUE_SIZE_LOG_FILE_PATH \
    --old_value_size_log_file_path=$OLD_VALUE_SIZE_LOG_FILE_PATH \
    --latency_threshold=$LATENCY_THRESHOLD \
    > /dev/null 2> /dev/null
